# 2.3 Linear Algebra

Can load datasets into tensors and manipulate these tensors with basic mathematical operations. To start building sophisticated models, will need a few tools from linear algebra. This section offers a gentle introduction to the most essential concepts

### 2.3.1 Scalers
Manipulating numbers one at a time. Formally, we call these values **scalars**.

For example, the temperature in Palo Alto is a balmy $72$ degrees Fahrenheit. If you wanted to convert the temperature to Celsius you would evaluate the expression $c = \frac{5}{9}(f - 32)$, setting $f$ to $72$. In this equation, the values $5$, $9$, and $32$ are constant scalars. The variables $c$ and $f$ in general represent unknown scalars.

We denote scalars by ordinary lower-cased letters (e.g., $x$, $y$, and $z$)and the space of all (continuous) *real-valued* scalars by $\mathbb{R}$.

Remember that the expression $x \in \mathbb{R}$
is a formal way to say that $x$ is a real-valued scalar.
The symbol $\in$ (pronounced "in")
denotes membership in a set.

(**Scalars are implemented as tensors 
that contain only one element.**)
Below, we assign two scalars
and perform the familiar addition, multiplication,
division, and exponentiation operations.

In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x-y, x*y, x/y, x**y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

### 2.3.2 Vectors

[**you can think of a vector as a fixed-length array of scalars.**].
Call these scalars the *elements* of the vector

For example, if we were training a model to predict the risk of a loan defaulting, might associate each applicant with a vector whose components correspond to quantities like their income, length of employment, or number of previous defaults.

If we were studying the risk of heart attack, each vector might represent a patient and its components might correspond to
their most recent vital signs, cholesterol levels, minutes of exercise per day, etc.

We denote vectors by bold lowercase letters, 
(e.g., $\mathbf{x}$, $\mathbf{y}$, and $\mathbf{z}$).

Vectors are implemented as $1^{\textrm{st}}$-order tensors.

In general, such tensors can have arbitrary lengths,
subject to memory limitations. Caution: in Python, as in most programming languages, vector indices start at $0$, also known as *zero-based indexing*, whereas in linear algebra subscripts begin at $1$ (one-based indexing).


In [5]:
x = torch.arange(3)

We can refer to an element of a vector by using a subscript.
For example, $x_2$ denotes the second element of $\mathbf{x}$. 
Since $x_2$ is a scalar, we do not bold it.
By default, we visualize vectors 
by stacking their elements vertically.

$$\mathbf{x} =\begin{bmatrix}x_{1}  \\ \vdots  \\x_{n}\end{bmatrix},$$


Here $x_1, \ldots, x_n$ are elements of the vector.
Later on, we will distinguish between such *column vectors*
and *row vectors* whose elements are stacked horizontally.
Recall that [**we access a tensor's elements via indexing.**]

In [6]:
x[2]

tensor(2)

To indicate that a vector contains $n$ elements,
we write $\mathbf{x} \in \mathbb{R}^n$.

Formally, we call $n$ the *dimensionality* of the vector.
[**In code, this corresponds to the tensor's length**],
accessible via Python's built-in `len` function.

In [7]:
len(x)

3

Can also access the length via the shape attribute. The shape is a tuple that indicates a tensor’s length along each axis. Tensors with just one axis have shapes with just one element.

In [8]:
x.shape

torch.Size([3])

The word “dimension” gets overloaded to mean both the number of axes and the length along a particular axis. 

To avoid this confusion, we use **order** to refer to the number of axes and **dimensionality** exclusively to refer to the number of components.

### 2.3.3 Matrices

Scalars are $0^{\textrm{th}}$-order tensors and vectors are $1^{\textrm{st}}$-order tensors, matrices are $2^{\textrm{nd}}$-order tensors.

Denote matrices by bold capital letters (e.g., $\mathbf{X}$, $\mathbf{Y}$, and $\mathbf{Z}$), and represent them in code by tensors with two axes.

The expression $\mathbf{A} \in \mathbb{R}^{m \times n}$
indicates that a matrix $\mathbf{A}$ contains $m \times n$ real-valued scalars, arranged as $m$ rows and $n$ columns.

When $m = n$, we say that a matrix is *square*.

Visually, can illustrate any matrix as a table. To refer to an individual element,we subscript both the row and column indices, e.g.,
$a_{ij}$ is the value that belongs to $\mathbf{A}$'s
$i^{\textrm{th}}$ row and $j^{\textrm{th}}$ column:

$$\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}.$$


In code, we represent a matrix $\mathbf{A} \in \mathbb{R}^{m \times n}$
by a $2^{\textrm{nd}}$-order tensor with shape ($m$, $n$).
[**We can convert any appropriately sized $m \times n$ tensor 
into an $m \times n$ matrix**] 
by passing the desired shape to `reshape`:


In [9]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Sometimes we want to flip the axes. When exchange a matrix's rows and columns, the result is called its *transpose*.

Formally, we signify a matrix $\mathbf{A}$'s transpose by $\mathbf{A}^\top$ and if $\mathbf{B} = \mathbf{A}^\top$, then $b_{ij} = a_{ji}$ for all $i$ and $j$.

Thus, the transpose of an $m \times n$ matrix is an $n \times m$ matrix:

$$
\mathbf{A}^\top =
\begin{bmatrix}
    a_{11} & a_{21} & \dots  & a_{m1} \\
    a_{12} & a_{22} & \dots  & a_{m2} \\
    \vdots & \vdots & \ddots  & \vdots \\
    a_{1n} & a_{2n} & \dots  & a_{mn}
\end{bmatrix}.
$$

In code, we can access any (**matrix's transpose**) as follows:

In [10]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

[**Symmetric matrices are the subset of square matrices
that are equal to their own transposes:
$\mathbf{A} = \mathbf{A}^\top$.**]
The following matrix is symmetric:

In [12]:
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

In [13]:
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Matrices are useful for representing datasets. 

Typically, rows correspond to individual records and columns correspond to distinct attributes.

### 2.3.4 Tensors

May need to work with higher-order [**tensors**]. Tensors (**give us a generic way of describing extensions to $n^{\textrm{th}}$-order arrays.**)

Call software objects of the *tensor class* "tensors" precisely because they too can have arbitrary numbers of axes.

Denote general tensors by capital letters with a special font face
(e.g., $\mathsf{X}$, $\mathsf{Y}$, and $\mathsf{Z}$)and their indexing mechanism (e.g., $x_{ijk}$ and $[\mathsf{X}]_{1, 2i-1, 3}$) 
follows naturally from that of matrices.

Tensors will become more important when working with images. Each image arrives as a $3^{\textrm{rd}}$-order tensor with axes corresponding to the height, width, and *channel*. At each spatial location, the intensities of each color (red, green, and blue)
are stacked along the channel. 

Furthermore, a collection of images is represented in code by a $4^{\textrm{th}}$-order tensor, where distinct images are indexed
along the first axis.

Higher-order tensors are constructed, as were vectors and matrices,
by growing the number of shape components.

In [14]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5 Basic Properties of Tensor Arithmetic

Scalars, vectors, matrices, and higher-order tensors
all have some handy properties. 

For example, elementwise operations produce outputs that have the 
same shape as their operands.

In [15]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()

In [16]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [19]:
B

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [20]:
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

The [**elementwise product of two matrices
is called their *Hadamard product***] (denoted $\odot$).
We can spell out the entries 
of the Hadamard product of two matrices 
$\mathbf{A}, \mathbf{B} \in \mathbb{R}^{m \times n}$:



$$
\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}.
$$

In [21]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

Adding or multiplying a scalar and a tensor produces a result with the same shape as the original tensor. Here, each element of the tensor is added to (or multiplied by) the scalar.

In [22]:
a = 2 
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [23]:
a + X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [25]:
a*X

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [26]:
(a*X).shape

torch.Size([2, 3, 4])

### 2.3.6 Reduction

Often, want to calculate [**the sum of a tensor's elements.**]
To express the sum of the elements in a vector $\mathbf{x}$ of length $n$, write $\sum_{i=1}^n x_i$. 

There is a simple function for it:

In [27]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [28]:
x = torch.arange(3, dtype=torch.float32)

In [30]:
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

To express [**sums over the elements of tensors of arbitrary shape**],
simply sum over all its axes. 

For example, the sum of the elements of an $m \times n$ matrix $\mathbf{A}$ could be written $\sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}$.

In [31]:
A.shape

torch.Size([2, 3])

In [32]:
A.sum()

tensor(15.)

By default, invoking the sum function *reduces* a tensor along all of its axes, eventually producing a scalar.

Our libraries also allow us to [**specify the axes along which the tensor should be reduced.**]

To sum over all elements along the rows (axis 0), we specify `axis=0` in `sum`. Since the input matrix reduces along axis 0 to generate the output vector, this axis is missing from the shape of the output.

In [33]:
A.shape

torch.Size([2, 3])

In [34]:
A.sum(axis=0).shape

torch.Size([3])

In [35]:
A.sum()

tensor(15.)

In [36]:
A.sum(axis=0)

tensor([3., 5., 7.])

Specifying `axis=1` will reduce the column dimension (axis 1) by summing up elements of all the columns.

In [37]:
A.shape

torch.Size([2, 3])

In [38]:
A.sum(axis=1)

tensor([ 3., 12.])

In [39]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [40]:
A.sum(axis=1).shape

torch.Size([2])

Reducing a matrix along both rows and columns via summation is equivalent to summing up all the elements of the matrix.

In [41]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

A related quantity is the **mean**, also called the **average**.

Calculate the mean by dividing the sum by the total number of elements. Because computing the mean is so common, it gets a dedicated library function that works analogously to sum.

In [42]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

Likewise, the function for calculating the mean can also reduce a tensor along specific axes.

In [ ]:
A.mean(axis=0), A.sum(axis=0)