# 2. Preliminaries

Will need a few skills:
- techniques for storing and manipulating data
- libraries for ingesting and preprocessing data from variety of sources
- knowledge of basic linear algebraic operations that can be applied to high-dimensional data
- enough calculus to determine which direction to adjust each parameter in order to decrease loss function
- ability to automatically compute derivatives 
- fluency in probability (primary language for reasoning under uncertainty
- apptitude for finding answers in documentation 

### 2.1 Data Manipulation

Need ways to manipulate data, generally two important tasks:
- acquire data
- process once its inside the computer

n-dimensional arrays are known as tensors

All modern deep learning framworks, tensor class resembles NumPy's ndarray class (with more features added)

- Tensor class supports automatic differntiation
- Leverages GPUs to accerlate numerical computation, whereas NumPy only runs on CPU 

These properties make neural networks easy to code and fast to run

In [1]:
import torch

A tensor represents array of numerical values (in any dimensions)

One-dimensional tensors are known as **vectors**

Two-dimensional tensors are known as **matrix**

K-dimensional, is known as a k-th order tensor

Pytorch offers many ways to create new tensors and prepopulating with values. Example arange(n), will create evenly spaced tensors starting at 0 (included) up to n (not included)

Default, the interval size is 1 (can be changed)

New tensors are stored in main memory and designated for CPU-based computations

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
y = torch.arange(10, dtype=torch.float32)
y

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Values are called **elements** of the tensor

tensor x contains 12 elements
tensor y contains 10 elements

Can inspect the total number of elements in a tensor using **numel** method

In [6]:
x.numel()

12

In [7]:
y.numel()

10

Can also see the shape of the tensor (length along each direction)

Because x is a vector, it will only have a single dimension

In [9]:
x.shape

torch.Size([12])

Can change the shape of a tensor without altering its size or values, by invoking **reshape** function 

For example, we can transform our vector x whose shape is (12,) to a matrix X with shape (3, 4). This new tensor retains all elements but reconfigures them into a matrix. Notice that the elements of our vector are laid out one row at a time and thus x[3] == X[0, 3].

In [10]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Note: specifying every shape component to reshape is redundant. Because we already know our tensor’s size, we can work out one component of the shape given the rest. 

To automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically. In our case, instead of calling x.reshape(3, 4), we could have equivalently called x.reshape(-1, 4) or x.reshape(3, -1).

Practitioners often need to work with tensors initialized to contain all 0s or 1s. We can construct a tensor with all elements set to 0 and a shape of (2, 3, 4) via the zeros function.

In [13]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.zeros((2,4,3,4))

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

Similarly, we can create a tensor with all 1s by invoking ones

In [17]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We often wabt to sample each element randomly (and independently) from a given probability distribution. 

For example, the **parameters of neural networks are often initialized randomly**. 

The following snippet creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.

In [18]:
torch.randn(3,4)

tensor([[-0.7670,  0.5252, -0.9545,  0.1566],
        [-1.5705,  0.8614, -0.2079, -0.4664],
        [-0.8039, -1.8453, -0.0884,  1.0441]])

Finally, we can construct tensors by supplying the exact values for each element by supplying (possibly nested) Python list(s) containing numerical literals. 

Here, we construct a matrix with a list of lists, where the outermost list corresponds to axis 0, and the inner list corresponds to axis 1.

In [19]:
torch.tensor([[2,1,3,4], [1,2,3,4], [4,3,2,1]])

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 Indexing and Slicing

As with Python lists, can access tensor elements by indexing (starting with 0). 

To access an element based on its position relative to the end of the list, we can use negative indexing. 

We can access whole ranges of indices via slicing (e.g., X[start:stop]), where the returned value includes the first index (start) but not the last (stop). 

When only one index (or slice) is specified for a kth-order tensor, it is applied along axis 0. Thus, in the following code, [-1] selects the last row and [1:3] selects the second and third rows.

In [20]:
X[-1]

tensor([ 8,  9, 10, 11])

In [21]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Beyond reading them, we can also write elements of a matrix by specifying indices.

In [30]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [31]:
X[1,2]= 17 # should change the 6 to a 17
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 17,  7],
        [ 8,  9, 10, 11]])